<?php
/** @var $block \GhoSter\FacebookComment\Block\Container\ProductTab */
$_product = $block->getProduct();
?>
<?php if($_product && $block->getFacebookCommentConfig()->isEnabled()): ?>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/<?php echo $block->getFacebookCommentConfig()->getLocale(); ?>/sdk.js#xfbml=1&version=v3.2&appId=<?php echo $block->getFacebookCommentConfig()->getAppId();?>&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <div class="fb-comments"
         data-colorscheme="<?php echo $block->getFacebookCommentConfig()->getTheme(); ?>"
         data-href="<?php echo $block->getProductUrl($_product); ?>"
         data-width="100%"
         data-numposts="<?php echo $block->getFacebookCommentConfig()->getLimitPost(); ?>"
         data-order-by="<?php echo $block->getFacebookCommentConfig()->getSortBy(); ?>"
         data-show-faces="<? echo $block->getFacebookCommentConfig()->getShowFace(); ?>"></div>
<?php endif; ?>