<?php
/** @var $block \GhoSter\FacebookComment\Block\ProductTab */
?>

<?php $_product = $block->getProduct(); ?>

<?php if($block->getAppId()): ?>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/<?php echo $block->getLocale(); ?>/sdk.js#xfbml=1&version=v3.2&appId=<?php echo $block->getAppId();?>&autoLogAppEvents=1';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <div class="fb-comments"
         data-colorscheme="<?php echo $block->getTheme(); ?>"
         data-href="<?php echo $block->getProductUrl($_product); ?>"
         data-width="100%"
         data-numposts="<?php echo $block->getNumberOfPost(); ?>"
         data-order-by="<?php echo $block->getOrderBy(); ?>"
         data-show-faces="true"></div>
<?php endif; ?>