<?php
/**
 * GhoSter FacebookComment
 *
 * @package        GhoSter_FacebookComment
 * @author         GhoSter
 * @copyright      Copyright (c) 2016, GhoSter Inc<thinghost.info>. All rights reserved
 */

/** @var $block \GhoSter\FacebookComment\Block\ProductTab */
?>

<?php $_product = $block->getProduct(); ?>

<div id="fb-root"></div>
<script>
    window.fbAsyncInit = function () {
        FB.init({
            appId: '911500158926800',
            xfbml: true,
            version: 'v2.8'
        });
        FB.AppEvents.logPageView();
    };

    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<div class="fb-comments" data-href="<?php echo $block->getProductUrl($_product); ?>" data-width="100%" data-numposts="8"></div>