<?php
/**
 * GhoSter FacebookComment
 *
 * @package        GhoSter_FacebookComment
 * @author         GhoSter
 * @copyright      Copyright (c) 2016, GhoSter Inc<thinghost.info>. All rights reserved
 */

/** @var $block \GhoSter\FacebookComment\Block\ProductTab */
?>

<?php $_product = $block->getProduct(); ?>
<?php $_colorscheme = $block->getData('theme'); ?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=911500158926800";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-comments" data-colorscheme="<?php echo $_colorscheme; ?>" data-href="<?php echo $block->getProductUrl($_product); ?>" data-width="100%" data-numposts="8" data-show-faces="true"></div>
